

CREATE OR REPLACE FUNCTION RETORNA_CATEGORIA
(p_COD PRODUTO_EXERCICIO.COD%TYPE) -- PARÂMETRO DE ENTRADA PARA QUANDO A FUNÇÃO FOR CHAMADA)

RETURN PRODUTO_EXERCICIO.CATEGORIA%TYPE

IS
  v_CATEGORIA PRODUTO_EXERCICIO.CATEGORIA%TYPE;

BEGIN
  SELECT CATEGORIA INTO v_CATEGORIA FROM PRODUTO_EXERCICIO WHERE COD = p_COD;
  RETURN v_CATEGORIA;

END;



SELECT COD AS CODIGO, RETORNA_CATEGORIA(COD) AS CATEGORIA FROM produto_exercicio WHERE COD = 67120;
SELECT * FROM PRODUTO_EXERCICIO;