
CREATE OR REPLACE FUNCTION categoria_cliente 
(p_FATURAMENTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE)

RETURN CLIENTE.CATEGORIA%TYPE

IS
  v_CATEGORIA CLIENTE.CATEGORIA%TYPE;

BEGIN
    IF    p_FATURAMENTO <= 10000 THEN
          v_CATEGORIA := 'PEQUENO';
    ELSIF p_FATURAMENTO <= 50000 THEN
          v_CATEGORIA := 'MÉDIO';
    ELSIF p_FATURAMENTO <= 100000 THEN
          v_CATEGORIA := 'MÉDIO GRANDE';
    ELSE  v_CATEGORIA := 'GRANDE';
    END IF;
    RETURN v_CATEGORIA;
END;




-- EXECUTANDO --
VARIABLE g_CATEGORIA VARCHAR2(100);
EXECUTE :g_CATEGORIA := categoria_cliente(90000);
PRINT g_CATEGORIA;


