
-- CRIANDO A FUNÇÃO
CREATE OR REPLACE FUNCTION obter_descricao_segmercado
(p_ID IN SEGMERCADO.ID%TYPE) -- 'p' de 'PARAMETER' (tanto para procedures quanto para funções)

RETURN SEGMERCADO.DESCRICAO%TYPE -- ESPECIFICA O TIPO DO RETORNO (nesse caso o mesmo tipo do campo "DESCRICAO" da tabela "SEGMERCADO")

IS
   v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
   v_ID SEGMERCADO.ID%TYPE;

BEGIN
   SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = p_ID;
   RETURN v_DESCRICAO; -- ESSE RETORNO DEVE SER DO MESMO TIPO QUE FOI ESPECIFICADO NO CAMPO "RETURN" (LINHA 5)
   
END;



-- EXECUTANDO A FUNÇÃO
SELECT ID, obter_descricao_segmercado(ID), DESCRICAO, LOWER(DESCRICAO) FROM SEGMERCADO WHERE ID = 1; -- 3 FORMAS DE RETORNAR O VALOR
SELECT ID, obter_descricao_segmercado(ID), DESCRICAO, LOWER(DESCRICAO) FROM SEGMERCADO ; -- SEM O 'WHERE', executa a função em todas as linhas