-- CLASSIFICAÇÃO DOS CLIENTES --

-- PEQUENO - FATURA ATÉ 10.000
-- MÉDIO - FATURA DE 10.001 ATÉ 50.000
-- MÉDIO GRANDE - FATURA DE 50.001 ATÉ 100.000
-- GRANDE - FATURA MAIS DE 100.000

SET SERVEROUTPUT ON

DECLARE
    v_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE := 50000;
    v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    IF v_FATURAMENTO <= 10000 THEN
       v_CATEGORIA := 'PEQUENO';
    ELSIF v_FATURAMENTO <= 50000 THEN
       v_CATEGORIA := 'MÉDIO';
    ELSIF v_FATURAMENTO <= 100000 THEN
       v_CATEGORIA := 'MÉDIO GRANDE';
    ELSE 
       v_CATEGORIA := 'GRANDE';
    END IF;
    dbms_output.put_line('A categoria é: ' || v_CATEGORIA);
  COMMIT;
    
END;