
-- CRIANDO A PROCEDURE --
CREATE OR REPLACE PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%TYPE,
p_RAZAO CLIENTE.RAZAO_SOCIAL%TYPE,
p_CNPJ CLIENTE.CNPJ%TYPE,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE,
p_CATEGORIA CLIENTE.CATEGORIA%TYPE
)

IS

BEGIN
  INSERT INTO CLIENTE
  VALUES (
     p_ID,
     p_RAZAO,
     p_CNPJ,
     p_SEGMERCADO,
     SYSDATE,
     p_FATURAMENTO,
     p_CATEGORIA 
     );
     COMMIT;
END;


-- EXECUTANDO A PROCEDURE --

SELECT * FROM CLIENTE;
SELECT * FROM SEGMERCADO;

EXECUTE incluir_cliente (1, 'SUPERMERCADOS CAMPEAO', '1234567890', '1', 90000, 'MEDIO GRANDE');